# Generated by Django 4.2.4 on 2023-08-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='UserName',
            new_name='authorUser',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='Rating',
            new_name='ratingaAuthor',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='relationsPost',
            new_name='commentPost',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='relationsUser',
            new_name='commentUser',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date_comment',
            new_name='dateCreation',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='rating_comment',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='text_comment',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Choise',
            new_name='categiryType',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='time',
            new_name='dataCategory',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='relations_category',
            new_name='postCategory',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='rating_content',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text_content',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='relations_OnCategory',
            new_name='categoryThrough',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='relations_post',
            new_name='postThrough',
        ),
        migrations.AlterField(
            model_name='category',
            name='NameCategory',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
