# Generated by Django 4.2.4 on 2023-08-15 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_username_author_authoruser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Turn_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='categiryType',
            new_name='categoryType',
        ),
    ]
