# Generated by Django 4.2.4 on 2023-08-17 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_turn_author_post_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='ratingaAuthor',
            new_name='ratingAuthor',
        ),
    ]
