# Generated by Django 4.2.4 on 2023-09-17 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0005_category_subscribers_usersubscribtion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(blank=True, through='news.UserSubscribtion', to=settings.AUTH_USER_MODEL),
        ),
    ]
