# Generated by Django 4.2.4 on 2023-09-20 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_category_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='categoryThrough',
            new_name='category',
        ),
    ]
