# Generated by Django 4.2.4 on 2023-09-29 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_rename_categorythrough_postcategory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='postCategory',
            new_name='category',
        ),
    ]
