# Generated by Django 4.2.4 on 2023-09-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_rename_postcategory_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoryType',
            field=models.CharField(choices=[('po', 'стихотворение'), ('so', 'песня')], default='po', max_length=2),
        ),
    ]
